# Generated by Django 3.2.9 on 2021-11-13 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=120)),
                ('segundo_nombre', models.CharField(blank=True, max_length=120)),
                ('primer_apellido', models.CharField(max_length=120)),
                ('segundo_apellido', models.CharField(blank=True, max_length=120)),
                ('identificacion', models.IntegerField(max_length=13)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.IntegerField(max_length=13)),
                ('confirmado', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
