# Generated by Django 3.2.9 on 2021-11-13 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
                ('ciudadId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='identificacionId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.tipoidentificacion'),
            preserve_default=False,
        ),
    ]
