# Generated by Django 3.2.9 on 2021-11-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211113_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='segundo_nombre',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.IntegerField(),
        ),
    ]
