# Generated by Django 3.2.9 on 2021-11-27 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cliente_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.direccion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio_compra', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('stock', models.IntegerField()),
                ('colorId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.color')),
                ('tipoProductoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.tipoproducto')),
            ],
        ),
    ]
