# Generated by Django 3.2.9 on 2021-12-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='This is a default description for the products'),
            preserve_default=False,
        ),
    ]
