# Generated by Django 3.2.9 on 2022-01-11 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.cliente')),
                ('productoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.producto')),
            ],
        ),
    ]
