# Generated by Django 3.2.9 on 2022-02-01 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_carro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.cliente')),
                ('estadoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unidad', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('productoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.producto')),
                ('ventaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.venta')),
            ],
        ),
    ]
