# Generated by Django 3.2.9 on 2022-02-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_estado_pedido_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
