# Generated by Django 3.2.9 on 2022-02-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_venta_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='direccion',
            field=models.CharField(default='Direccion de mi mami', max_length=280),
            preserve_default=False,
        ),
    ]
