# Generated by Django 4.0.5 on 2022-06-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='referencia',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
