# Generated by Django 4.0.5 on 2022-06-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('body', models.CharField(max_length=10000)),
                ('imagen', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.FileField(upload_to='media/'),
        ),
    ]
