# Generated by Django 4.0.5 on 2022-06-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_consejo_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consejo',
            name='body',
            field=models.TextField(max_length=10000),
        ),
    ]
